#!/usr/bin/env sh

if [ -z "$(docker image ls | grep ddt-phpunit)" ]; then
docker build -t ddt-phpunit:latest . -f - <<EOF
FROM php:8.0-alpine
RUN apk add --no-cache composer linux-headers php-xml php-dom php-tokenizer php-ctype php-xmlwriter
RUN apk add --no-cache --virtual .build-deps \$PHPIZE_DEPS \
    && pecl install xdebug \
    && docker-php-ext-enable xdebug \
    && apk del -f .build-deps
COPY ./phpunit-entrypoint /phpunit-entrypoint
RUN chmod +x /phpunit-entrypoint
ENTRYPOINT ["/phpunit-entrypoint"]
EOF
fi

docker run -v ${PWD}:/tools -w /tools ddt-phpunit:latest sh -c "composer install && ./vendor/bin/phpunit $@"
